insert INTO persona(id, nombre, apellido, boleta, password) values(nextval('persona_seq'), 'Juan', 'Perez','2008600903','test' );

insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15734, 'Atletismo', 10.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15055, 'Básquetbol', 6.5);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15620, 'Béisbol', 5.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15100, 'Box', 12.8);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),02050, 'Físico constructivismo', 6.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15210, 'Fútbol americano', 8.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15605, 'Fútbol soccer', 10.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15430, 'Karate', 10.3);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15730, 'Lucha olímpica', 6.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),02070, 'Remo', 8.5);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15620, 'Softball', 5.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15430, 'Taekwondo', 10.3);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15675, 'Tenis', 7.3);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15010, 'Tiro con arco', 4.3);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15230, 'Tocho bandera', 8.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15710, 'Voleibol', 4.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15731, 'Frontón', 7.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),09013, 'Ajedrez', 1.5);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15430, 'Judo', 10.3);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),18260, 'Natación', 10.3);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15138, 'Animación', 6.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15300, 'Gimnasia', 3.8);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),15590, 'Patinaje', 7.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),01015, 'Ciclismo', 7.5);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),02052, 'Pesas', 6.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),02048, 'Elíptica', 5.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),12180, 'Caminadora', 10.0);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),2019, 'Bicicleta estática', 8.5);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),2022, 'Calistenia', 3.8);
insert into actividad( id, codigo, nombre, mets) values(nextval('actividad_seq'),12150, 'Correr', 8.0);

